// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_tastyfish_TMBExports
#include <TMB.hpp>
#include "LFPM.hpp"
#include "NLFPM.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "LFPM") {
    return LFPM(this);
  } else if(model == "NLFPM") {
    return NLFPM(this);
  } else {
    error("Unknown model.");
  }
  return 0;
}
